version: 1
formatters:
  simple:
    format: '%(levelname)s - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    filename: main.log
    formatter: simple
root:
  handlers: [file]