name: Dyck1
lang_fam: Dyck
batch_size: 32
multiple: False
num_par: 1
num_val_bins: 3
p_val: 0.5
q_val: 0.25
lower_window: 2
upper_window: 50
training_size: 10000
test_size: 2000
debug: False
min_depth: 0
max_depth: -1
len_incr: 50
bin1_lower_window: 2
bin1_upper_window: 100
bin1_lower_depth: 0
bin1_upper_depth: -1
vary_len: False
vary_depth: False