name: Shuffle2
lang_fam: Shuffle
batch_size: 32
multiple: True
chunk_size: 2
num_val_bins: 3
lower_window: 2
upper_window: 50
training_size: 10000
test_size: 2000
len_incr: 50
lower_depth: 0
upper_depth: -1
p_val: 0.5
q_val: 0.25
num_par: 2
bin_lower_depth: 0
bin_upper_depth: -1