name: Tomita-1
lang_fam: Tomita
batch_size: 32
multiple: True
chunk_size: 2
num_val_bins: 2
num_par: 1
lower_window: 1
upper_window: 100
test_size: 50
training_size: 1000
leak: True
unique: True
debug: False
len_incr: 50